Modified README.md
codex-team/devops-toolbox-agent pull request #14
Opened 2021-02-22 06:00 UTC by Xemka

1. Упрощена структура README.md, добавлена ссылка на загрузку исполняемого файла.

2021-02-22 08:13 UTC, talyguryn requested changes

2021-02-22 08:13 UTC, talyguryn commented on README.md
> +##[Download](https://github.com/codex-team/devops-toolbox-agent/releases/latest/download/devops-toolbox-agent) for Linux
```suggestion

[Download](https://github.com/codex-team/devops-toolbox-agent/releases/latest/download/devops-toolbox-agent) for Linux
```

2021-02-22 08:13 UTC, talyguryn commented on README.md
> +Parameter  | Description | |
рассыпалась таблица

2021-02-22 08:13 UTC, talyguryn commented on README.md
> +*cron schedule [template](https://crontab.guru)*
не жалей пустых строк в ридми

```suggestion
*cron schedule [template](https://crontab.guru)* 

```

2021-02-22 08:13 UTC, talyguryn commented on README.md
> +### **Other parameters (.env)**
```suggestion
### Other parameters (.env)
```

2021-02-22 08:13 UTC, talyguryn commented on README.md
>  ### **Example:**
тут и так заголовок. зачем ещё раз добавлять жирность

```suggestion
### Example
```

2021-02-22 08:13 UTC, talyguryn commented on README.md
>  # DevOps Toolbox Agent
надо после этой строчки добавить кратное описание этой тулы. тип, что это приложение, которое крутится у вас на сервере, собирает данные и метрики и куда-то передает

2021-02-22 10:46 UTC, ilyamore88 commented on README.md
> +## [Download](https://github.com/codex-team/devops-toolbox-agent/releases/latest/download/devops-toolbox-agent) for Linux
```suggestion
[Download](https://github.com/codex-team/devops-toolbox-agent/releases/latest/download/devops-toolbox-agent) for Linux
```

2021-02-22 13:48 UTC, talyguryn commented on README.md
> +## [Download](https://github.com/codex-team/devops-toolbox-agent/releases/latest/download/devops-toolbox-agent) for Linux
ага 😬👍

![image](https://user-images.githubusercontent.com/15259299/108716914-ba080d00-752d-11eb-85e1-c57baa9e4f75.png)

2021-02-23 18:10 UTC, ilyamore88 approved these changes
Ещё бы ревью от Саши

2021-02-23 18:28 UTC, talyguryn approved these changes

2021-02-23 18:48 UTC, n0str approved these changes

2021-02-23 18:51 UTC, merged