Feature/add cron
codex-team/devops-toolbox-agent pull request #2
Opened 2020-11-25 10:35 UTC by kebyo

Подключить модуль для запуска работы агента по расписания (раз в какой-то период агент будет запускаться проверять сервисы и отправлять данные на сервак). В рамках задачи надо только научить агента запускаться по расписанию и отправлять на сервер фейковые данные.

2020-11-25 17:03 UTC, ilyamore88 commented on .env.example
> +Token=k2bk2gbjfe4ifhweofhow5ed
```suggestion
TOKEN=k2bk2gbjfe4ifhweofhow5ed
```

2020-11-25 17:03 UTC, ilyamore88 commented on .env.example
> +Token=k2bk2gbjfe4ifhweofhow5ed
И убрать бы токен из example

2020-11-25 17:03 UTC, ilyamore88 commented on src/index.ts
> +  console.log(await res.json());
Этот log убрать бы

2020-11-25 18:06 UTC, ilyamore88 commented on src/config/index.ts
> + *
Пустой док

2020-11-25 18:18 UTC, neSpecc commented on src/cron/index.ts
> + * Class Cron
плохое описание. Надо написать зачем этот класс, что он делает и как его использовать

2020-11-25 18:18 UTC, neSpecc commented on src/cron/index.ts
> +export default class Cron {
давай назовем более обще: TaskManager или Sheduler

2020-11-26 13:23 UTC, ilyamore88 approved these changes

2020-11-26 14:08 UTC, neSpecc requested changes

2020-11-26 14:08 UTC, neSpecc commented on src/index.ts
> + * Task Manager will send current services on the server on a schedule
```suggestion
 * Task Manager will send current services to the API by a schedule
```

2020-11-26 14:08 UTC, neSpecc commented on src/taskManager/index.ts
> +   * @private scheduledTask - scheduled task
Описание дублирует название. `@private` и название свойства не нужно писать. Просто понятное описание с большой буквы. 

Описание должно отвечать не на вопрос `Что это`, а на вопрос `Для чего это`.

2020-11-26 14:08 UTC, neSpecc commented on src/taskManager/index.ts
> +   * @param schedule - schedule
плохие описания

2020-11-26 14:08 UTC, neSpecc commented on src/types/index.ts
> +export {
не описано

2020-11-26 14:08 UTC, neSpecc commented on src/types/service.ts
> + * Interface for service
Плохое описание

2020-11-26 14:08 UTC, neSpecc commented on src/types/service.ts
> +   * Service type
Плохое описание

2020-11-26 14:08 UTC, neSpecc commented on src/types/service.ts
> +   * Service payload
и тут тоже

2020-11-26 14:08 UTC, neSpecc commented on src/utils/protocol/types/requestMessage.ts
> +interface RequestMessage extends Message {
думаю, тут нет смысла выделять отдельный тип

2020-11-26 15:53 UTC, kebyo commented on src/utils/protocol/types/requestMessage.ts
> +interface RequestMessage extends Message {
А почему бы не придерживаться структуры протокола? Мы же хотели в будущем вынести весь протокол  в отдельный npm пакет

2020-11-26 16:06 UTC, neSpecc approved these changes

2020-11-26 16:06 UTC, neSpecc commented on src/utils/protocol/types/requestMessage.ts
> +interface RequestMessage extends Message {
да, но суть протокола в общении по сокетам. А тут обычный аякс-запрос на роут, который даже не транспортом обрабатывается

2020-11-26 18:30 UTC, nikmel2803 approved these changes

2020-11-26 19:32 UTC, merged