Feature/nginx parser
codex-team/devops-toolbox-agent pull request #6
Opened 2020-12-08 21:35 UTC by kebyo

Added nginx config parser

2020-12-16 14:16 UTC, neSpecc approved these changes

2020-12-24 17:51 UTC, neSpecc requested changes

2020-12-24 17:51 UTC, neSpecc commented on .env.example
> +NGINX_DIR=/etc/nginx
env не нужно использовать. Приложение же билдится в исполняемый файл

2020-12-24 18:04 UTC, neSpecc approved these changes

2020-12-24 21:11 UTC, ilyamore88 approved these changes
Протестировал
![image](https://user-images.githubusercontent.com/37909603/103106347-bea36880-4645-11eb-99ee-4764be0da443.png)

2020-12-25 17:03 UTC, merged