Remove env
codex-team/devops-toolbox-agent pull request #9
Opened 2020-12-24 17:51 UTC by fabled228

Env usage removed, agrs are taken from the command line

2020-12-24 18:35 UTC, neSpecc requested changes
readme missed

2020-12-25 13:07 UTC, neSpecc requested changes

2020-12-25 13:07 UTC, neSpecc commented on README.md
> +_API_URL_
API URL не надо передавать, пользователи его не должны знать

2020-12-25 13:07 UTC, neSpecc commented on README.md
> +The running command requires 3 parameters:
непонятный перенос строки. Это новый абзац или продолжение предыдущего?

2020-12-25 13:07 UTC, neSpecc commented on README.md
> +_SCHEDULE_
не описано как пользоваться `shedule`

2020-12-25 13:07 UTC, neSpecc commented on README.md
> +`npm run start --API_URL="http://localhost:3000/services" --SCHEDULE="* * * * *" --TOKEN="" --NGINX_DIR=""`
почему npm run? агент это же бинарный файл

2020-12-25 13:07 UTC, neSpecc commented on src/config/index.ts
> +    description: 'Api url',
описаня повторяют названия, а не объявняют ничего

2020-12-25 13:10 UTC, fabled228 commented on README.md
> +The running command requires 3 parameters:
Просто перечисление параметров друг под другом, сделать в строку?

2020-12-25 13:12 UTC, neSpecc commented on README.md
> +The running command requires 3 parameters:
я бы убрал `To run agent you should use npm or yarn.`. Агент это бинарник, ему не нужны yarn и npm и даже js

2020-12-25 14:10 UTC, fabled228 commented on README.md
> +The running command requires 3 parameters:
А как будут передаваться параметры, используя консоль?

2020-12-25 14:48 UTC, neSpecc commented on README.md
> +The running command requires 3 parameters:
я не знаю как это делается, надо поресерчить

2020-12-25 14:50 UTC, neSpecc commented on README.md
> +The running command requires 3 parameters:
Возможно точно также, через `yargs`, надо протестить

> Command line call to packaged app `./app a b` is equivalent to `node app.js a b`

https://github.com/vercel/pkg#usage-of-packaged-app

2020-12-25 14:54 UTC, ilyamore88 commented on README.md
> +_--NGINX_DIR_
```suggestion
_NGINX_DIR_
```

2020-12-25 14:54 UTC, ilyamore88 commented on README.md
> +_--NGINX_DIR_
Я ведь могу не указывать этот параметр? Он должен иметь в коде дефолтное значение `/etc/nginx`.

2020-12-25 15:08 UTC, fabled228 commented on README.md
> +_--NGINX_DIR_
fixed

2020-12-25 15:08 UTC, fabled228 commented on src/config/index.ts
> +    description: 'Api url',
fixed

2020-12-25 15:08 UTC, fabled228 commented on README.md
> +_SCHEDULE_
fixed

2020-12-25 15:22 UTC, fabled228 commented on README.md
> +_API_URL_
вернуть и env и из него брать или харкодить?

2020-12-25 18:36 UTC, ilyamore88 commented on README.md
> +_NGINX_DIR_(optional)
Вёрстка сломана
Пропиши для nginx_dir, что там дефолтный путь /etc/nginx
И вообще, это можно вынести в отдельную таблицу вместе с описанием этих параметров как в строке 40

2020-12-25 18:36 UTC, ilyamore88 commented on README.md
> +_NGINX_DIR_(optional)
И строку 40 бы тогда перенести в таблицу и убрать

2020-12-26 16:58 UTC, neSpecc requested changes

2020-12-26 16:58 UTC, neSpecc commented on README.md
> +`start devops-toolbox-agent-win.exe '--SCHEDULE="* * * * *" --TOKEN="" --NGINX_DIR=""'`
не понятно, это инлайн код в одну строку или блочный код? Если блочный, надо выделить его с помощью «```» и отделить друг от друга пустой строкой

2020-12-26 16:58 UTC, neSpecc commented on README.md
> +_TOKEN_
почему курсив, а не инлайн код? и где пустая строка между абзацами

2020-12-26 16:58 UTC, neSpecc commented on README.md
> +_NGINX_DIR_(default path is __/etc/nginx__)
тут все в кашу слилось

2020-12-26 16:58 UTC, neSpecc commented on README.md
> +_SCHEDULE_ is Cron schedule(guide below):
пробелов не хватает

2020-12-26 16:58 UTC, neSpecc commented on README.md
> +### Allowed fields
к чему относится заг?

2020-12-26 16:58 UTC, neSpecc commented on README.md
> +
тут не помешает пример

2020-12-26 16:58 UTC, neSpecc commented on src/config/index.ts
> +  public static schedule: string = argv.SCHEDULE!;
пропали описания

2020-12-26 17:35 UTC, fabled228 commented on README.md
> +### Allowed fields
schedule guide

2020-12-29 17:58 UTC, neSpecc requested changes
Плохое оформление ридми

2020-12-29 19:05 UTC, ilyamore88 approved these changes

2020-12-29 19:41 UTC, neSpecc approved these changes

2020-12-29 19:42 UTC, merged